- hosts: terraform-ansible
  tasks:
  - name: Instalando o python3, virtualenv
    apt: 
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes  
  - name: Git Clone 
    ansible.builtin.git: 
      repo: https://github.com/alura-cursos/clientes-leo-api.git
      dest: /home/ubuntu/tcc
      version: master
  - name: Instalando dependÃªncias com pip (Djando e Django Rest)
    pip: 
      virtualenv: /home/ubuntu/tcc/venv
      name: 
       - django
       - djangorestframework
  - name: Iniciando o projeto
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
    ignore_errors: yes
  - name: Alterando o host do settings
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regexp:  'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
    